### ISSUE TITLE
api endpoints example formats?

### ISSUE THREAD

**Issue by Inside4ndroid** [avirupdebnath/MyOTTApp#2]
can you provide examples of the returned data from the api so i can build my own api?

`    public static final String carousalURL="https://wg2lkz962h.execute-api.ap-south-1.amazonaws.com/api/Carousel/GetBannersBYConfigId/";
    public static final String searchURL="https://4085ty7z1e.execute-api.ap-south-1.amazonaws.com/api/Search/GetByKey/";
    public static final String movieByfilterURL="https://4085ty7z1e.execute-api.ap-south-1.amazonaws.com/api/Search/GetByFilter";
    public static final String movieCategoriesURL="https://wg2lkz962h.execute-api.ap-south-1.amazonaws.com/api/Master/GetAllCategories";
    public static final String movieDetailsByIdURL="https://wg2lkz962h.execute-api.ap-south-1.amazonaws.com/api/Movie/GetById/";
    public static final String getAllLanguagesURL="https://wg2lkz962h.execute-api.ap-south-1.amazonaws.com/api/Master/GetAllLanguages";
    public static final String seriesDetailsByIdURL="https://wg2lkz962h.execute-api.ap-south-1.amazonaws.com/api/Series/GetById/";
    public static final String episodesBySeasonIdURL="https://wg2lkz962h.execute-api.ap-south-1.amazonaws.com/api/Series/GetEpisodesBySeasonId/";
    public static final String movieByMultiFilterURL="";
    public static final String trackUserWatchHistoryURL="https://w4nwo1e47k.execute-api.ap-south-1.amazonaws.com/api/Track/GetWatchHistory";`

Thanks :P

**Comment by avirupdebnath** [comment]
You can check the models folder for the respective models(formats) returned by the urls.

**Comment by mannisingla** [comment]
Can you please provide sample API responses

**Comment by avirupdebnath** [comment]
Check the models/Dtos and the url references in the code. That would give you the idea of the all the API response structure.
